define({
    singularHoursAgo : '{x} час назад',
    genSingularHoursAgo : '{x} часа назад',
    genPluralHoursAgo :'{x} часов назад',
    singularMinutesAgo : '{x} минута назад',
    genSingularMinutesAgo : '{x} минуты назад',
    genPluralMinutesAgo : '{x} минут назад',
    lessThanAMinuteAgo : 'Меньше минуты назад',
    changeYourLocation : 'Изменить местонахождение',
    enterTownPostcode : 'Введите город или почтовый индекс',
    loading : 'Загрузка',
    localNewsAndWeather : 'Местные новости и погода',
    localNewsCouldNotBeLoaded : 'Местные новости не загружаются',
    pleaseWait : 'Подождите, пожалуйста',
    retry : 'Повторить',
    search : 'Поиск',
    sendAnotherComment : 'Отправить другой комментарий',
    showMore : 'Показать ещё',
    showLess : 'Свернуть',
    locationSettingNotAvailable : 'К сожалению, локализация здесь недоступна',
    useMyLocationNotAvailable : 'К сожалению, опция "использовать локализацию" сейчас недоступна',
    anErrorHasOccured : 'К сожалению, произошла ошибка. Попробуйте ещё раз',
    locationSettingIsNotCurrentlyAvailable : 'К сожалению, установки локализации сейчас недоступны',
    errorTryingToDetectLocation : 'Произошла ошибка в процессе локализации. Попробуйте ещё раз',
    searchResults : 'Результаты поиска:',
    searchTerm : 'Поисковый запрос',
    section : 'Разделы',
    noResults : 'Результат отсутствует',
    thereWasAProblem : 'Произошла ошибка; попробуйте ещё раз',
    unableToDetectLocation : 'Не удаётся установить местонахождение',
    useMyLocation : 'Использовать локализацию',
    locationBetweenCountries : 'Выбранное Вами место находится между двумя странами [или административными/географическими единицами]. Чтобы установить своё местонахождение, пожалуйста, выберите ближайшую к Вам страну.',
    moreInfo : 'Текст целиком',
    lessInfo : 'Коротко',
    errorAudio :   'Аудио не поддерживается вашим устройством',
    errorLive :    'Прямая трансляция не поддерживается вашим устройством',
    errorContent : 'Материал недоступен',
    errorDefault : 'Ваше устройство не поддерживает воспроизведение',
    downloadMessageVideo : 'Выберите вариант загрузки',
    downloadMessageAudio : 'Загрузить аудиофайл',
    play : 'Воспроизвести',
    nowPlaying : "Воспроизводится",
    mediaUnavailable : 'Файл недоступен',
    navMoreButton: 'Еще',
    navMoreLabel: 'Разделы',
    navFooterSectionsButton: 'Разделы',
    live: 'Live:',
    watch: 'Смотреть:'
});
