/**
 * © 2015 Cedexis Inc.
 * Radar JavaScript client
 * Application Version: 0.1.276
 * Build Timestamp: 1449774146
 */
(function(window,document){'use strict';function m(e){var h=e.bb||18,g=e.cb||21,c,f,k,l;this.g=e.w;this.Y=e.d;this.ka=e.samplerId;this.K=[];this.g.cedexis=this.g.cedexis||{};this.g.cedexis.callbacks=this.g.cedexis.callbacks||[];this.Fa=e.w&&e.w.location&&/radar-no-ajax/i.test(e.w.location.search)?!1:e.w.XMLHttpRequest&&"undefined"!==typeof(new e.w.XMLHttpRequest).withCredentials?!0:!1;this.Ja=function(){return c};this.Ka=function(){return document};this.Aa=function(a,b){for(var d=[],c=0;100>c&&(0<a.length||0<b.length);)0<a.length&&
d.push(a.shift()),0<b.length&&d.push(b.shift()),c+=1;return d};this.I=function(){return(new Date).getTime()};this.v=function(a,b){return setTimeout(a,b)};this.o=function(a){clearTimeout(a)};this.y64enc=this.P=function(){return function(a){var b="",d,c,f,e,g,h,k=0;a=a.replace(/\r\n/g,"\n");c="";for(f=0;f<a.length;f+=1)e=a.charCodeAt(f),128>e?c+=String.fromCharCode(e):(127<e&&2048>e?c+=String.fromCharCode(e>>6|192):(c+=String.fromCharCode(e>>12|224),c+=String.fromCharCode(e>>6&63|128)),c+=String.fromCharCode(e&
63|128));for(a=c;k<a.length;)d=a.charCodeAt(k),k+=1,c=a.charCodeAt(k),k+=1,f=a.charCodeAt(k),k+=1,e=d>>2,d=(d&3)<<4|c>>4,g=(c&15)<<2|f>>6,h=f&63,isNaN(c)?g=h=64:isNaN(f)&&(h=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(e)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._-".charAt(h);return b}}();
this.ba=function(a){var b=/radar_(tags|impact)_(\w{3,})/i,d;if(("radar_tags_"===a.slice(0,11)||"radar_impact_"===a.slice(0,13))&&(b=b.exec(a))&&3===b.length){try{d=p(window[a])}catch(c){return null}return b[2]+":"+this.P(d)}return null};this.H=function(a){if(!a.includePartnerTags)return"0";if(!window.JSON||"function"!==typeof window.JSON.stringify)return"1";if(a=a.getImpactObject()){var b;try{b=p(a)}catch(c){return"error"}try{b=this.P(b)}catch(c){return"error"}return"impact_kpi:"+b}b=[];for(var d in window){a=
null;if(void 0!==window.hasOwnProperty)window.hasOwnProperty(d)&&(a=this.ba(d));else try{void 0!==window[d]&&(a=this.ba(d))}catch(c){}a&&b.push(a)}return 1>b.length?"0":b.join("@")};this.D=function(a){var b=document.getElementById("cdx");b||(b=document.createElement("div"),b.id="cdx",document.body.appendChild(b));b.appendChild(a)};this.ca=function(){return Math.random()};this.Ma=function(a){return Math.floor(this.ca()*(a-0+1))+0};this.N=function(a,b){var d,c=[];b=b||"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
for(d=0;d<a;d+=1)c.push(b.charAt(this.Ma(b.length-1)));return c.join("")};this.xa=function(a){return/http:/i.test(a)?"http":/https:/i.test(a)?"https":/\/\//.test(a)?window.location.protocol.replace(":",""):null};this.ua=function(){var a=[],b=c.p.p,d,f;b.a&&b.a.a?a.push({a:"cold",b:1,f:!!b.d,t:b.a.a.t,u:b.a.a.u}):b.b&&b.b.a&&a.push({a:"cold",b:1,f:!!b.d,t:b.b.a.t,u:b.b.a.u});b.d&&a.push({a:"uni",t:b.d.t,u:b.d.u});if(b.a)for(b.a.b&&a.push({a:"rtt",b:0,f:!!b.d,t:b.a.b.t,u:b.a.b.u}),f=c.b,d=0;d<f;d++)b.a.c&&
a.push({a:"kbps",b:14,f:!!b.d,t:b.a.c.t,u:b.a.c.u,report:f-1===d,probeIdSuffix:0===d?"":String.fromCharCode(97+d)});else if(b.b)for(b.b.b&&a.push({a:"rtt",b:0,f:!!b.d,t:b.b.b.t,u:b.b.b.u}),f=c.b,d=0;d<f;d++)b.b.c&&a.push({a:"kbps",b:14,f:!!b.d,t:b.b.c.t,u:b.b.c.u,report:f-1===d,probeIdSuffix:0===d?"":String.fromCharCode(97+d)});b.c&&(d=this.xa(b.c.u))&&("http:"!==this.g.location.protocol&&"https"!==d||a.push({a:"custom",b:2,f:!!b.d,t:b.c.t,u:b.c.u}));c.L=a};this.va=function(a){var b=[];a.connect&&
b.push({a:"cold",b:1,f:!1,t:1,u:a.connect});a.response_time&&b.push({a:"rtt",b:0,f:!1,t:1,u:a.response_time});a.kbps&&b.push({a:"kbps",b:14,f:!1,t:1,u:a.kbps});c.L=b};this.ab=function(a){return"uni"===a?[c.requestor.zoneId,c.requestor.customerId,c.p.z,c.p.c,c.p.i,this.N(8),c.requestor.requestSignature].join("-"):[a,c.requestor.zoneId,c.requestor.customerId,c.p.z,c.p.c,c.p.i,c.requestor.transactionId,c.requestor.requestSignature].join("-")};this.A=function(a,b){var d="";a=a||f.u;if(!1!==c.a){d="?rnd=";
-1<a.indexOf("?",0)&&(d="&rnd=");var e;"uni"===f.a?e="uni":e=f.b+(b||"");d+=this.ab(e)}return a+d};this.Ra=function(a){var b=a.indexOf("//");if(-1<b){var d=a.substring(b+2),c="//";0<b&&(c=a.substring(0,b)+"//");a=d.split("/");a[0]=this.N(63,"abcdefghijklmnopqrstuvwxyz")+"."+a[0];return c+a.join("/")}return null};this.M=function(a,b){var d=/(\d+)kb\./i.exec(b);return!d||2>d.length?0:Math.floor(8E3*parseInt(d[1],10)/a)};this.B=function(a){var b,d,e;if(c&&f){c.c?(b=c.c.a,d=c.c.b,e=c.c.c):(b=c.p.z,d=
c.p.c,e=c.p.i);q(this,"Success",b,d,e,f.b,0,a);var g=c.requestor;a=[g.domains.report,"f1",g.requestSignature,b,d,e,f.b,0,a,k||"0",this.H(g)];this.C("//"+a.join("/"));this.v(this.ma(),200)}};this.ma=function(){var a=this;return function(){a.h()}};this.Va=function(){var a=this;return function(){a.l()}};this.j=function(a){var b,d,e;if(c&&f){c.c?(b=c.c.a,d=c.c.b,e=c.c.c):(b=c.p.z,d=c.p.c,e=c.p.i);q(this,"Error",b,d,e,f.b,a,0);var g=c.requestor;a=[g.domains.report,"f1",g.requestSignature,b,d,e,f.b,a,0,
k||"0",this.H(g)];this.C("//"+a.join("/"));this.v(this.Va(),200)}};this.G=function(a){return!0===a.f&&null===k};this.$=function(a,b,d){a===f&&(b=d.call(null,b),0<b&&4E3>=b?(d=b,14===a.b&&(d=this.M(b,a.u)),this.G(a)?(l={probe:a,measurement:d},this.h()):this.B(d)):this.j(1))};this.na=function(a,b,d){var c=this;return function(){a.c||(c.o(a.e),c.$(a,b,d))}};this.O=function(a){var b,d;b=document.createElement("script");b.async=!0;b.src=this.A();f.c=!1;f.d="loading";d=this.I();void 0!==b.onreadystatechange?
b.onreadystatechange=function(b,c){var e=!1;return function(){e||"loaded"!==this.readyState&&"complete"!==this.readyState||(e=!0,c!==f||c.c||(b.o(c.e),b.$(c,d,a)))}}(this,f):b.onload=this.na(f,d,a);b.onerror=function(a,b){return function(){b===f&&(a.o(b.e),b.c=!0,b.d="error",a.j(4))}}(this,f);f.e=this.v(this.F(),4E3);window.radar.stoppedAt=window.cedexis.radar.stopped_at=null;this.D(b)};this.ea=function(){var a=this;return function(b){return a.I()-b}};this.F=function(a){var b=this,d=f;return function(){var c=
1;d.c||(a&&a.call(null),d===f&&("loaded"===d.d&&(c=4),d.c=!0,d.d="timeout",b.j(c)))}};this.Qa=function(){var a=this;return function(){k="2";a.J()}};this.Ta=function(){var a=this,b=f,d;return d=function(){a.o(b.e);this.removeEventListener("load",d,!1);b.c||(b.d="loaded")}};this.Ua=function(a,b){return function(){a.removeEventListener("load",b,!1)}};this.Sa=function(){var a=this,b=f,d;return d=function(e){function g(a,b){var d=[u.domains.report,"f1",u.requestSignature,h.p.z,h.p.c,h.p.i,b,v,n];q(a,"DSA",
h.p.z,h.p.c,h.p.i,b,v,n);d.push(k||"0");d.push(a.H(u));d.push(h.m.ciphertext);a.C("//"+d.join("/"))}if(b===f){var h;try{h=JSON.parse(e.data)}catch(D){}if(h&&h.source&&"dsa"===h.source&&"l"!==h.s&&(window.removeEventListener("message",d,!1),"s"===h.s&&!b.c)){var n=h.m.responseEnd-h.m.domainLookupStart,u=c.requestor,v=0;if(4E3>=n){if(a.G(b)){l={probe:b,measurement:n,extraFields:[h.m.ciphertext]};a.h();return}g(a,1);g(a,0)}else v=1,n=0,g(a,1);a.l()}}}};this.ha=function(){var a=document.createElement("iframe"),
b=this.A(),d=this.Ta();window.addEventListener("message",this.Sa(),!1);a.addEventListener("load",d,!1);a.src=b;a.style.display="none";f.c=!1;f.d="loading";f.e=this.v(this.F(this.Ua(a,d)),4E3);this.D(a)};this.X=function(){this.O(function(a){return window.radar.stoppedAt?window.radar.stoppedAt.getTime()-a:window.cedexis.radar.stopped_at?window.cedexis.radar.stopped_at.getTime()-a:null})};this.Wa=function(a,b){var d=this;return function(){d.o(a.e);d.B(d.I()-b)}};this.ga=function(){var a=this.Ka().createElement("iframe"),
b=this.I();a.src=this.A();a.style.display="none";f.c=!1;f.d="loading";a.onload=this.Wa(f,b);f.e=this.v(this.F(),4E3);this.D(a)};this.aa=function(a){if(this.g.performance&&this.g.performance.getEntriesByType)for(var b=this.g.performance.getEntriesByType("resource"),d=b.length;d--;)if(b[d].name===a)return b[d];return null};this.Ia=function(a){var b=this.g.performance;if(b&&"getEntriesByName"in b)return b.getEntriesByName(a)};this.Xa=function(a){var b=this;return function(){if(f===a&&(b.o(a.e),!a.c&&
"loading"===a.d))if(a.d="loaded","report"in a&&!a.report)b.h();else{var d=b.aa(this.src);if(d){var c,e=14===a.b;0<d.requestStart?(c=e?Math.round(d.responseEnd-d.requestStart):Math.round(d.responseStart-d.requestStart),1>c&&0<d.duration&&(c=Math.round(d.duration))):c=Math.round(d.duration);1>c?b.l():0<c&&4E3>=c?(d=c,e&&(d=b.M(c,a.u)),b.G(a)?(l={probe:a,measurement:d},b.h()):b.B(d)):b.j(1)}}}};this.Za=function(a,b){var d=(new Date).getTime(),c=this;return function(){c.o(a.e);var e=(new Date).getTime();
a.c||(e-=d,e>b?c.j(1):c.G(a)?(l={probe:a,measurement:e},c.h()):c.B(e))}};this.Ya=function(a){var b=this;return function(){b.o(a.e);if(!a.c){var d=b.aa(this.src);d&&(d=0<d.requestStart?Math.round(d.domainLookupEnd-d.domainLookupStart):Math.round(d.duration),1>d?b.l():4E3>=d?b.B(d):b.j(1))}}};this.fa=function(a){var b=this;return function(){f===a&&(b.o(a.e),a.c||"loading"!==a.d||(a.c=!0,a.d="error",b.j(4)))}};this.ia=function(){var a="cold"===f.a,b="performance"in this.g&&"getEntriesByType"in this.g.performance,
d=a&&!b;a||b?(a=c.timeout||4E3,b=new Image,b.onload=d?this.Za(f,a):this.Xa(f),b.onerror=this.fa(f),f.c=!1,f.d="loading",f.e=this.v(this.F(),a),b.src=this.A(void 0,f.probeIdSuffix||null)):this.h()};this.ta=function(){var a=new Image;a.onload=this.Ya(f);a.onerror=this.fa(f);f.c=!1;f.d="loading";f.e=this.v(this.F(),4E3);var b=this.Ra(f.u);b?a.src=this.A(b):this.h()};this.sa=function(){if("performance"in this.g&&"getEntriesByType"in this.g.performance&&this.Fa){var a=this.A(),b=new XMLHttpRequest,d=this.Pa(f,
a);b.addEventListener("load",d);b.addEventListener("error",d);b.addEventListener("abort",d);b.addEventListener("timeout",d);b.open("GET",a,!0);b.timeout=c.timeout||4E3;b.send()}else this.l()};this.Pa=function(a,b){var d=this,e=!1;return function(g){if(c&&a===f&&!e){e=!0;var h=c.requestor,k=h.getImpactObject()||{};k.metadata=k.metadata||{};k.metadata.providers=k.metadata.providers||{};k.metadata.providers[c.p.i]=k.metadata.providers[c.p.i]||{};var l=k.metadata.providers[c.p.i][a.b]={};h.setImpactObject(k);
l.event=g.type;switch(g.type){case "load":l.status="undefined"===typeof this.status?"unknown":this.status;l.readyState="undefined"===typeof this.readyState?"unknown":this.readyState;l.statusText="undefined"===typeof this.statusText?"unknown":this.statusText;200===this.status?(g=d.Ia(b))&&g.length?(l.contentAsBase36Int=parseInt(this.responseText,36),d.wa(a,g[g.length-1])):d.l():d.j(1);break;case "timeout":d.j(1);break;case "error":case "abort":d.j(4)}}}};this.wa=function(a,b){var d,c=14===a.b;d=0<
b.requestStart?c?Math.round(b.responseEnd-b.requestStart):Math.round(b.responseStart-b.requestStart):Math.round(b.duration);if(1>d)this.l();else if(0<d&&4E3>=d){var e=d;c&&(e=this.M(d,a.u));this.G(a)?(l={probe:a,measurement:e},this.h()):this.B(e)}else this.j(1)};this.J=function(){function a(a,c){var g=[b.domains.report,"f1",b.requestSignature,d,e,f,c,0,l.measurement,k||"0",a.H(b)];if("extraFields"in l)for(var h=0;h<l.extraFields.length;h+=1)g.push(l.extraFields[h]);q(a,"Success",d,e,f,c,0,l.measurement);
a.C("//"+g.join("/"))}if(c)if(l){var b=c.requestor,d,e,f;c.c?(d=c.c.a,e=c.c.b,f=c.c.c):(d=c.p.z,e=c.p.c,f=c.p.i);4===l.probe.t?(a(this,1),a(this,0),this.l()):(a(this,l.probe.b),this.h())}else this.h()};this.pa=function(a){var b=this;return function(d){f!==a||c.p.i!==d.id||a.c||(a.d="loaded",k=d.node,b.J())}};this.ra=function(){return function(){}};this.qa=function(){return function(){}};this.Da=function(){var a,b;a=document.createElement("script");b=this.A();window.cdx=window.cdx||{};window.cdx.s=
window.cdx.s||{};window.cdx.s.b=this.pa(f);a.onload=this.ra();a.onerror=this.qa();f.c=!1;f.d="loading";a.type="text/javascript";a.async=!0;a.src=b;this.D(a)};this.oa=function(){var a=this;return function(b){var d,e,g;if(c&&f){try{d=JSON.parse(b.data)}catch(h){}d&&"uni"===d.source&&(b=parseInt(d.p.z,10),e=parseInt(d.p.c,10),g=parseInt(d.p.i,10),g===c.p.i&&e===c.p.c&&b===c.p.z&&d.r.z===c.requestor.zoneId&&d.r.c===c.requestor.customerId&&(a.o(f.e),"l"===d.s?f.d="loaded":-1<"es".indexOf(d.s)&&("e"===
d.s?(f.d="error",k="2"):"s"===d.s&&(!1===d.encoded&&(d.node_id=encodeURIComponent("base64:"+window.cedexis.base64.encode(d.node_id))),k=d.node_id),a.J())))}}};this.Ea=function(){return"function"===typeof window.postMessage&&"function"===typeof window.addEventListener};this.Ca=function(){var a;this.Ea()?(f.c=!1,f.d="loading",a=document.createElement("iframe"),a.style.display="none",a.src=this.A(),f.e=this.v(this.Qa(),4E3),this.D(a)):(k="1",this.J())};this.La=function(a){a=a.slice(a.lastIndexOf("/")+
1);var b=[/cdx10b/,/rdr12/,/radar\.js/,/r\d+(-\d+kb)?\.js/i,/r\d+\w+(-\d+kb)?\.js/i],c;if("d17.html"===a)return 4;for(c=0;c<b.length;c+=1)if(b[c].test(a))return 1;return/\.js(\?)?/i.test(a)?5:/\.(ico|png|bmp|gif|jpg|jpeg)(\?)?/i.test(a)?2:/\.(htm(l)?)(\?)?/i.test(a)?3:null};this.Ba=function(){var a;if(f)switch(f.t){case 1:this.X();break;case 2:this.ia();break;case 3:this.ga();break;case 4:this.ha();break;case 5:this.O(this.ea());break;case 6:a=this.La(f.u);switch(a){case 1:this.X();break;case 2:this.ia();
break;case 3:this.ga();break;case 4:this.ha();break;case 5:this.O(this.ea());break;default:this.j(5)}break;case 7:this.Ca();break;case 8:this.Da();break;case 9:this.ta();break;case 10:this.sa();break;default:this.j(6)}};this.h=function(){c&&(0<c.L.length?(f=c.L.shift(),this.Ba()):(c=null,this.l()))};this.l=function(){c=f=null;0<this.K.length?(l=k=null,c=this.K.shift(),r(this,"Cedexis Measure Provider",{providerOwnerZoneId:c.p.z,providerOwnerCustomerId:c.p.c,providerId:c.p.i}),c.p.source_url?this.ya():
(this.ua(),this.h())):r(this,"Cedexis Radar Session Finished")};this.ya=function(){var a,b,d;window.XMLHttpRequest&&(b=new window.XMLHttpRequest)&&(a=c.p.source_url,d=Math.ceil(99999999*this.ca()),a=0>a.indexOf("?",0)?a+("?rnd="+d):a+("&rnd="+d),b.open("GET",a,!0),b.onreadystatechange=this.la(),b.send())};this.la=function(){var a=this,b=c;return function(){var d;200===this.status&&4===this.readyState&&(d=JSON.parse(this.responseText),b===c&&(a.va(d),0<c.L.length?a.h():a.l()))}};this.Na=function(){var a=
0;window.chrome&&window.chrome.loadTimes?(a=window.chrome.loadTimes(),a=Math.round(1E3*a.firstPaintTime)):window.performance&&window.performance.timing&&window.performance.timing.msFirstPaint&&(a=Math.round(window.performance.timing.msFirstPaint));return a};this.$a=function(a){return this.da(a,a.transactionId)};this.da=function(a,b){if(this.g.location&&this.g.location.protocol){var c="https:"===this.g.location.protocol?"s":"i",e=[];e.push("i1");e.push(this.ka);e.push(h);e.push(g);e.push(a.zoneId);
e.push(a.customerId);e.push(b.toString(10));e.push(c);e=e.join("-");c=[];c.push(e+".init."+a.domains.init);c.push("i1");c.push(Math.floor((new Date).getTime()/1E3).toString(10));c.push(b.toString(10));c.push("xml");c="//"+c.join("/");return c+("?seed="+e)}return""};this.Oa=function(a,b){for(var c=0;c<a.length;c+=1)a[c].requestor=b;this.K=this.Aa(this.K,a);this.Ja()||this.l()};this.run=this.za=function(a){a.runCalledAt=(new Date).getTime();var b=this.g.performance;if(b){var c=b.setResourceTimingBufferSize||
b.webkitSetResourceTimingBufferSize;c&&c.call(b,300)}t({a:this.$a(a),b:w(this,a)});"afterRun"in a&&a.afterRun()};"function"===typeof window.addEventListener&&window.addEventListener("message",this.oa(),!1)}m.prototype.ja="navigationStart unloadEventStart unloadEventEnd redirectStart redirectEnd fetchStart domainLookupStart domainLookupEnd connectStart connectEnd secureConnectionStart requestStart responseStart responseEnd domLoading domInteractive domContentLoadedEventStart domContentLoadedEventEnd domComplete loadEventStart loadEventEnd".split(" ");
function q(e,h,g,c,f,k,l,a){r(e,"Cedexis Send "+h+" Report",{providerOwnerZoneId:g,providerOwnerCustomerId:c,providerId:f,probeId:k,resultCode:l,value:a})}
function r(e,h,g){for(var c=e.g.cedexis,f=c.callbacks,k=f.length;k--;)"function"===typeof f[k]&&f[k].call(e.g,h,g);for(var l in c.requestors)c.requestors.hasOwnProperty(l)&&c.requestors[l].sendParentMessages&&e.g.parent&&"function"===typeof e.g.parent.postMessage&&e.g.parent.postMessage({radar:{type:"status",data:{messageName:h,messageData:g}}},"*");if("dispatchEvent"in e.Y&&"CustomEvent"in e.g){var a;try{a=new CustomEvent(h,{detail:g})}catch(b){"Object doesn't support this action"===b.message&&(a=
document.createEvent("CustomEvent"),a.initCustomEvent(h,!1,!1,g))}a&&e.Y.dispatchEvent(a)}}m.prototype.log=function(e){var h=this.g.console;h&&h.log&&h.log.call(h,(new Date).toUTCString()+": "+e)};
m.prototype.Ha=function(){if(this.g.performance&&this.g.performance.getEntriesByType){for(var e=this.g.performance.getEntriesByType("resource"),h=e.length,g={},c;h--;){var f=e[h];c=f.name.split("//");if(c[1]){c=c[1].split("/");c=g[c[0]]=g[c[0]]||{V:0,W:0,R:0,S:0};var k,l;0<f.requestStart?(l=Math.round(f.responseEnd-f.requestStart),k=Math.round(f.responseStart-f.requestStart)):k=l=Math.round(f.duration);9<k&&(c.V+=k,c.R+=1);9<l&&(c.W+=l,c.S+=1);k=Math.round(f.startTime);c.U="undefined"===typeof c.U?
k:Math.min(k,c.U);k=Math.round(f.responseEnd);c.T="undefined"===typeof c.T?k:Math.max(k,c.T)}}var e=[],a;for(a in g)g.hasOwnProperty(a)&&(c=g[a],e.push([a,c.V,c.W,c.R,c.U,c.T,c.S]));return e}return null};m.prototype.getDomainPerformance=m.prototype.Ha;
function x(e,h){var g=(e.g.performance||{}).timing;if(g){if(0===g.loadEventEnd){e.Z=e.g.setInterval(y(e,h),1E3);return}for(var c=[h.domains.report,"n1",0],f=0;f<e.ja.length;f+=1){var k=g[e.ja[f]];c.push(void 0===k?0:k)}c.push(h.requestSignature);c.push(e.H(h));c.push(e.Na());g.connectEnd<g.connectStart||g.domainLookupEnd<g.domainLookupStart||g.domComplete<g.domLoading||g.fetchStart<g.navigationStart||g.loadEventEnd<g.loadEventStart||g.loadEventEnd<g.navigationStart||g.responseEnd<g.responseStart||
g.responseStart<g.requestStart||e.C("//"+c.join("/"))}Math.random()<h.remoteProbingSampleRate&&z(e,h)}function y(e,h){var g=20;return function(){0<g--?0<e.g.performance.timing.loadEventEnd&&(e.g.clearInterval(e.Z),x(e,h)):(e.g.clearInterval(e.Z),Math.random()<h.remoteProbingSampleRate&&z(e,h))}}
function p(e){function h(e,c){for(var f="",h=0;h<e.length;h++)f=c(f,e[h],h);return f}switch(typeof e){case "string":return'"'+(""+e).replace(/\"/g,'\\"')+'"';case "number":return isNaN(e)?"null":e;case "boolean":return e?"true":"false";case "undefined":return"null";default:return null===e?"null":""+e!==e&&"[object Array]"==Object.prototype.toString.call(e)?"["+h(e,function(e,c){return e+","+p(c)}).substring(1)+"]":"{"+h(function(e){var c=[],f;for(f in e)c.push(f);return c}(e),function(g,c){void 0!==
e[c]&&"function"!==typeof e[c]&&(g+=","+p(c)+":"+p(e[c]));return g}).substring(1)+"}"}};m.prototype.ka="j1";function t(e){var h=new XMLHttpRequest;e.c=e.c||{};if(h)try{h.open("GET",e.a,!0),"b"in e&&(h.onreadystatechange=function(){200===this.status&&4===this.readyState&&e.b.call(this)}),e.d&&(h.timeout=e.d),h.send()}catch(g){}}
function w(e,h){return function(){if(this.responseText){var g=/<requestSignature>([\w@]+)</.exec(this.responseText);g&&2===g.length&&(h.requestSignature=g[1],h.requestSignatureTimestamp=(new Date).getTime(),h.notify("init"),h.sendPLT&&Math.random()<h.pltSampleRate?x(e,h):Math.random()<h.remoteProbingSampleRate&&z(e,h))}}}m.prototype.C=function(e){t({a:e})};m.prototype.send_report=m.prototype.C;
function z(e,h){var g,c;g=[];var f="",k=h.deviceCaps.call(h),l=Object.keys(k);for(c=l.length;c--;)g.push(l[c]+"="+k[l[c]]);if(window.location&&window.location.search)for((c=/radar-location=\w+-\w+-\w+/.exec(window.location.search))&&g.push(c[0]),k=window.location.search.slice(1).split("&"),c=k.length;c--;)if(l=k[c].split("="),2===l.length)switch(l[0]){case "radar-geo":l=l[1].split("-");g.push("country="+l[0]);g.push("asn="+l[1]);break;case "radar-provider-count":g.push("providerCount="+l[1]);break;
case "radar-provider-count-public":g.push("providerCountPublic="+l[1]);break;case "radar-provider-count-private":g.push("providerCountPrivate="+l[1]);break;case "radar-providers-set":g.push("providersSet="+l[1])}else 1===l.length&&"radar-include-tiny-networks"==l[0]&&g.push("alwaysMeasureTinyNetworks");0<g.length&&(f="?"+g.join("&"));g=[h.domains.code,h.zoneId,h.customerId,"radar",h.buildTimestamp,e.N(20),"providers.json"];g="//"+g.join("/")+f;t({a:g,b:function(a){return function(){var b;try{b=JSON.parse(this.responseText)}catch(c){return}a.Oa(b,
h)}}(e)})}m.prototype.Ga=function(e,h){if("function"===typeof h){var g;var c;(c=this.g.crypto||this.g.msCrypto)&&c.getRandomValues?(g=new Uint32Array(1),c.getRandomValues(g),g=g[0]):g=Math.floor(1E9*Math.random());t({a:this.da(e,g),b:h})}};m.prototype.doInitWithCallback=m.prototype.Ga;window.cedexis.main=window.cedexis.main||new m({w:window,d:document,samplerId:"j1"});var A,B,C;if(window.cedexis.requestors)for(A=Object.keys(window.cedexis.requestors),B=A.length;B--;)C=window.cedexis.requestors[A[B]],C.transactionId&&!C.runCalledAt&&window.cedexis.main.run(C);}(window,document));