(function(){var k=this;function l(){}
function m(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}function aa(a){var b=m(a);return"array"==b||"object"==b&&"number"==typeof a.length}function n(a){return"string"==typeof a}function p(a){return"function"==m(a)}function q(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}
function ca(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function r(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ca;return r.apply(null,arguments)}
function u(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)c.length||void 0===b?d[f]?d=d[f]:d=d[f]={}:d[f]=b}function v(a,b){function c(){}c.prototype=b.prototype;a.B=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.w=function(a,c,e){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[c].apply(a,g)}};function w(a,b){this.c=a;this.f=b;this.b=0;this.a=null}function x(a){var b;0<a.b?(a.b--,b=a.a,a.a=b.next,b.next=null):b=a.c();return b}function da(a,b){a.f(b);100>a.b&&(a.b++,b.next=a.a,a.a=b)};function ea(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function fa(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ga=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function ha(a){if(!ia.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ja,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ka,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(la,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(ma,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(na,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(oa,"&#0;"));return a}var ja=/&/g,ka=/</g,la=/>/g,ma=/"/g,na=/'/g,oa=/\x00/g,ia=/[\x00&<>"']/;
function y(a,b){return a<b?-1:a>b?1:0};var z;a:{var pa=k.navigator;if(pa){var qa=pa.userAgent;if(qa){z=qa;break a}}z=""}function A(a){return-1!=z.indexOf(a)};function B(a){if(Error.captureStackTrace)Error.captureStackTrace(this,B);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}v(B,Error);B.prototype.name="CustomError";function ra(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var sa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ta(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<sa.length;e++)c=sa[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var va=new w(function(){return new ua},function(a){a.reset()});function wa(){var a=xa,b=null;a.a&&(b=a.a,a.a=a.a.next,a.a||(a.b=null),b.next=null);return b}function ua(){this.next=this.b=this.a=null}ua.prototype.reset=function(){this.next=this.b=this.a=null};var ya=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=n(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},za=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=n(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return!0;return!1};function Aa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ba(a){k.setTimeout(function(){throw a;},0)}var F;
function Ca(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!A("Presto")&&(a=function(){var a=document.createElement("IFRAME");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=r(function(a){if(("*"==d||a.origin==d)&&a.data==
c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!A("Trident")&&!A("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var a=c.o;c.o=null;a()}};return function(a){d.next={o:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?function(a){var b=document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};function Da(a,b){G||Ea();H||(G(),H=!0);var c=xa,d=x(va);d.a=a;d.b=b;d.next=null;c.b?c.b.next=d:c.a=d;c.b=d}var G;function Ea(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve(void 0);G=function(){a.then(Fa)}}else G=function(){var a=Fa;!p(k.setImmediate)||k.Window&&k.Window.prototype&&!A("Edge")&&k.Window.prototype.setImmediate==k.setImmediate?(F||(F=Ca()),F(a)):k.setImmediate(a)}}var H=!1,xa=new function(){this.b=this.a=null};
function Fa(){for(var a=null;a=wa();){try{a.a.call(a.b)}catch(b){Ba(b)}da(va,a)}H=!1};function I(a,b){this.a=J;this.i=void 0;this.c=this.b=this.f=null;this.g=this.h=!1;if(a!=l)try{var c=this;a.call(b,function(a){K(c,L,a)},function(a){K(c,M,a)})}catch(d){K(this,M,d)}}var J=0,L=2,M=3;function Ga(){this.next=this.c=this.b=this.f=this.a=null;this.g=!1}Ga.prototype.reset=function(){this.c=this.b=this.f=this.a=null;this.g=!1};var Ha=new w(function(){return new Ga},function(a){a.reset()});function Ia(a,b,c){var d=x(Ha);d.f=a;d.b=b;d.c=c;return d}
I.prototype.then=function(a,b,c){return Ja(this,p(a)?a:null,p(b)?b:null,c)};ea(I);function Ka(a,b){a.b||a.a!=L&&a.a!=M||La(a);a.c?a.c.next=b:a.b=b;a.c=b}function Ja(a,b,c,d){var f=Ia(null,null,null);f.a=new I(function(a,g){f.f=b?function(c){try{var f=b.call(d,c);a(f)}catch(C){g(C)}}:a;f.b=c?function(b){try{var f=c.call(d,b);a(f)}catch(C){g(C)}}:g});f.a.f=a;Ka(a,f);return f.a}I.prototype.l=function(a){this.a=J;K(this,L,a)};I.prototype.m=function(a){this.a=J;K(this,M,a)};
function K(a,b,c){if(a.a==J){a==c&&(b=M,c=new TypeError("Promise cannot resolve to itself"));a.a=1;var d;a:{var f=c,e=a.l,g=a.m;if(f instanceof I)Ka(f,Ia(e||l,g||null,a)),d=!0;else if(fa(f))f.then(e,g,a),d=!0;else{if(q(f))try{var h=f.then;if(p(h)){Ma(f,h,e,g,a);d=!0;break a}}catch(t){g.call(a,t);d=!0;break a}d=!1}}d||(a.i=c,a.a=b,a.f=null,La(a),b!=M||Na(a,c))}}function Ma(a,b,c,d,f){function e(a){h||(h=!0,d.call(f,a))}function g(a){h||(h=!0,c.call(f,a))}var h=!1;try{b.call(a,g,e)}catch(t){e(t)}}
function La(a){a.h||(a.h=!0,Da(a.j,a))}function Oa(a){var b=null;a.b&&(b=a.b,a.b=b.next,b.next=null);a.b||(a.c=null);return b}I.prototype.j=function(){for(var a=null;a=Oa(this);){var b=this.a,c=this.i;if(b==M&&a.b&&!a.g)for(var d=void 0,d=this;d&&d.g;d=d.f)d.g=!1;if(a.a)a.a.f=null,Pa(a,b,c);else try{a.g?a.f.call(a.c):Pa(a,b,c)}catch(f){Qa.call(null,f)}da(Ha,a)}this.h=!1};function Pa(a,b,c){b==L?a.f.call(a.c,c):a.b&&a.b.call(a.c,c)}function Na(a,b){a.g=!0;Da(function(){a.g&&Qa.call(null,b)})}
var Qa=Ba;var Ra=A("Opera")||A("OPR"),N=A("Trident")||A("MSIE"),Sa=A("Edge"),O=A("Gecko")&&!(-1!=z.toLowerCase().indexOf("webkit")&&!A("Edge"))&&!(A("Trident")||A("MSIE"))&&!A("Edge"),Ta=-1!=z.toLowerCase().indexOf("webkit")&&!A("Edge");function Ua(){var a=z;if(O)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Sa)return/Edge\/([\d\.]+)/.exec(a);if(N)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ta)return/WebKit\/(\S+)/.exec(a)}function Va(){var a=k.document;return a?a.documentMode:void 0}
var Wa=function(){if(Ra&&k.opera){var a;var b=k.opera.version;try{a=b()}catch(c){a=b}return a}a="";(b=Ua())&&(a=b?b[1]:"");return N&&(b=Va(),b>parseFloat(a))?String(b):a}(),Xa={};
function P(a){var b;if(!(b=Xa[a])){b=0;for(var c=ga(String(Wa)).split("."),d=ga(String(a)).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",h=d[e]||"",t=RegExp("(\\d*)(\\D*)","g"),C=RegExp("(\\d*)(\\D*)","g");do{var D=t.exec(g)||["","",""],E=C.exec(h)||["","",""];if(0==D[0].length&&0==E[0].length)break;b=y(0==D[1].length?0:parseInt(D[1],10),0==E[1].length?0:parseInt(E[1],10))||y(0==D[2].length,0==E[2].length)||y(D[2],E[2])}while(0==b)}b=Xa[a]=0<=b}return b}
var Ya=k.document,Za=Ya&&N?Va()||("CSS1Compat"==Ya.compatMode?parseInt(Wa,10):5):void 0;var $a=!N||9<=Number(Za);!O&&!N||N&&9<=Number(Za)||O&&P("1.9.1");N&&P("9");var ab=N||Ra||Ta;function bb(a,b){ra(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:cb.hasOwnProperty(d)?a.setAttribute(cb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var cb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function db(a,b,c){function d(c){c&&b.appendChild(n(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];if(!aa(e)||q(e)&&0<e.nodeType)d(e);else{var g;a:{if(e&&"number"==typeof e.length){if(q(e)){g="function"==typeof e.item||"string"==typeof e.item;break a}if(p(e)){g="function"==typeof e.item;break a}}g=!1}ya(g?Aa(e):e,d)}}};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function Q(a,b){this.f=[];this.u=b||null;this.a=this.b=!1;this.c=void 0;this.l=this.m=this.h=!1;this.g=0;this.i=null;this.s=0}Q.prototype.j=function(a,b){this.h=!1;R(this,a,b)};function R(a,b,c){a.b=!0;a.c=c;a.a=!b;eb(a)}function S(a){if(a.b){if(!a.l)throw new T;a.l=!1}}function U(a,b){V(a,b,b,void 0)}function V(a,b,c,d){a.f.push([b,c,d]);a.b&&eb(a)}Q.prototype.then=function(a,b,c){var d,f,e=new I(function(a,b){d=a;f=b});V(this,d,function(a){f(a)});return e.then(a,b,c)};ea(Q);
function fb(a){return za(a.f,function(a){return p(a[1])})}
function eb(a){if(a.g&&a.b&&fb(a)){var b=a.g,c=W[b];c&&(k.clearTimeout(c.a),delete W[b]);a.g=0}a.i&&(a.i.s--,delete a.i);for(var b=a.c,d=c=!1;a.f.length&&!a.h;){var f=a.f.shift(),e=f[0],g=f[1],f=f[2];if(e=a.a?g:e)try{var h=e.call(f||a.u,b);void 0!==h&&(a.a=a.a&&(h==b||h instanceof Error),a.c=b=h);if(fa(b)||"function"===typeof k.Promise&&b instanceof k.Promise)d=!0,a.h=!0}catch(t){b=t,a.a=!0,fb(a)||(c=!0)}}a.c=b;d&&(h=r(a.j,a,!0),d=r(a.j,a,!1),b instanceof Q?(V(b,h,d),b.m=!0):b.then(h,d));c&&(b=new gb(b),
W[b.a]=b,a.g=b.a)}function T(){B.call(this)}v(T,B);T.prototype.message="Deferred has already fired";T.prototype.name="AlreadyCalledError";function gb(a){this.a=k.setTimeout(r(this.c,this),0);this.b=a}gb.prototype.c=function(){delete W[this.a];throw this.b;};var W={};function hb(){var a={},b=a.document||document,c=document.createElement("SCRIPT"),d={a:c,v:void 0},f=new Q(0,d),e=null,g=null!=a.timeout?a.timeout:5E3;0<g&&(e=window.setTimeout(function(){X(c,!0);var a=new Y(ib,"Timeout reached for loading script //mediametrics.ru/partner/inject/online.jsonp.ru.js");S(f);R(f,!1,a)},g),d.v=e);c.onload=c.onreadystatechange=function(){c.readyState&&"loaded"!=c.readyState&&"complete"!=c.readyState||(X(c,a.A||!1,e),S(f),R(f,!0,null))};c.onerror=function(){X(c,!0,e);var a=
new Y(jb,"Error while loading script //mediametrics.ru/partner/inject/online.jsonp.ru.js");S(f);R(f,!1,a)};d=a.attributes||{};ta(d,{type:"text/javascript",charset:"UTF-8",src:"//mediametrics.ru/partner/inject/online.jsonp.ru.js"});bb(c,d);kb(b).appendChild(c)}function kb(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}
function X(a,b,c){null!=c&&k.clearTimeout(c);a.onload=l;a.onerror=l;a.onreadystatechange=l;b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}var jb=0,ib=1;function Y(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);B.call(this,c)}v(Y,B);var Z;var lb=new I(l);K(lb,L,void 0);Z=lb;u("mediametrics.Dao.getArticles",function(a,b){var c=new Q;null!=b&&p(b)&&U(c,b);Z=Z.then(function(){return new I(function(b){window.callbackJsonpMediametrics=function(b){var d=[];if("array"==m(b)&&0<b.length)for(var g=0,h=b.length;g<a&&g<h;g++)d.push(b[g]);S(c);R(c,!0,d)};U(c,function(){delete window.callbackJsonpMediametrics});hb();U(c,b)})})});u("mediametrics.Dom.appendChild",function(a,b){a.appendChild(b)});
u("mediametrics.Dom.createDom",function(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!$a&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',ha(g.name),'"');if(g.type){e.push(' type="',ha(g.type),'"');var h={};ta(h,g);delete h.type;g=h}e.push(">");e=e.join("")}e=f.createElement(e);g&&(n(g)?e.className=g:"array"==m(g)?e.className=g.join(" "):bb(e,g));2<d.length&&db(f,e,d);return e});u("mediametrics.Dom.createTextNode",function(a){return document.createTextNode(String(a))});
u("mediametrics.Dom.getElement",function(a){var b=document;return n(a)?b.getElementById(a):a});u("mediametrics.Dom.getParentElement",function(a){var b;if(ab&&!(N&&P("9")&&!P("10")&&k.SVGElement&&a instanceof k.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return q(b)&&1==b.nodeType?b:null});u("mediametrics.version","1.1");})();
