
clean:	
	cd someco-mvn-tutorial-repo; mvn clean
	cd someco-mvn-tutorial-repo; rm -f *.log *.log.*
	cd someco-mvn-tutorial-repo; rm -fr alf_data_dev/*
	cd someco-mvn-tutorial-share; mvn clean
	cd someco-mvn-tutorial-share; rm -f *.log *.log.*
	cd webscripts-tutorial-repo; mvn clean



